### PR TITLE
Update batch.R - Sets the maximum time (in seconds) to wait while try…

### PR DESCRIPTION
**Pull request by wangzhao0217**
Sets the maximum time (in seconds) to wait while trying to connect to the server. This only limits the connection phase, not the entire request.

By adding httr::config(connecttimeout = 60 * 60 * 5), allowing the connection phase to take up to 5 hours, matching overall timeout.

### CODE REVIEW

**Comment by wangzhao0217** [comment]
@Robinlovelace

**Review by Robinlovelace — APPROVED** [review]

**Comment by Robinlovelace** [comment]
Let's see if the tests pass, will merge if so!

**Review by Robinlovelace — CHANGES_REQUESTED** [review]
Tests not passing:

```
 ** using staged installation
** R
Error in parse(...) : 
  /home/runner/work/cyclestreets-r/cyclestreets-r/check/cyclestreets.Rcheck/00_pkg_src/cyclestreets/R/batch.R:310:3: unexpected symbol
309:   res = httr::POST(url = batch_url, body = body, httr::timeout(60*60*5), httr::config(connecttimeout = 60 * 60 * 5) # Connection timeout (5 hours))
310:   res_json
       ^
ERROR: unable to collate and parse R files for package ‘cyclestreets’
* removing ‘/home/runner/work/cyclestreets-r/cyclestreets-r/check/cyclestreets.Rcheck/cyclestreets’

```

Source: https://github.com/cyclestreets/cyclestreets-r/actions/runs/12128460223/job/33841523400?pr=95#step:6:92

Have you tried `devtools::check()` @wangzhao0217 ?

**Comment by wangzhao0217** [comment]
close with a new PR

**Pull request closed without merging**
